### ISSUE TITLE
Issue: Add 404 page

### ISSUE THREAD

**Issue by caesar44bc** [caesar44bc/photo-gallery#4]
### Is your proposal related to a problem?

Currently, when users try to access a non-existent page, they are not presented with a user-friendly error page. This can lead to confusion and a poor user experience.

### Describe the solution you'd like

The solution is to implement a custom **404 error page** that will display when users attempt to navigate to a non-existent route. The page should:
- Include a clear message like "Page Not Found" or "Oops! This page doesn't exist."
- Provide a link to redirect users back to the homepage.
- Be visually consistent with the overall design of the platform.

### Additional context

Consider adding some fun or creative elements (e.g., illustrations or witty text) to make the error page more engaging. Ensure that the page is mobile-friendly and accessible.

**Comment by Musaveershaik** [comment]
Interesting. I would like to contribute Will you please assign this to me
